# redis配置，以下有默认配置的也可以使用默认配置
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
    timeout: 0
  server:
    port: 8088
    servlet:
      context-path: /mysbt
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/dqc?useUnicode=true&characterEncoding=utf8
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: 1234
      initial-size: 15
      max-active: 50
      min-idle: 15
      time-between-eviction-runs-millis: 300000
      min-evictable-idle-time-millis: 600000
      #type指定数据源
      type: com.alibaba.druid.pool.DruidDataSource
    
#公共配置与profiles选择无关
  mybatis:
    typeAliasesPackage: com.crh.entity
    mapperLocations: classpath:mapper/*.xml
# spring.datasource.type=com.zaxxer.hikari.HikariDataSource
# spring.datasource.type=org.apache.tomcat.jdbc.pool.DataSource
# spring.datasource.type=org.apache.commons.dbcp.BasicDataSource
# spring.datasource.type=org.apache.commons.dbcp2.BasicDataSource